version: 1

seeds:
  - name: column_metadata
    config:
      database: edbi_teamg01
      schema: config
      contract:
        enforced: true
    columns:
      - name: source_name
        data_type: string
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('ingestion_metadata')
              field: source_name
      - name: source_column
        data_type: string
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: target_column
        data_type: string
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: data_type
        data_type: string
        constraints:
          - type: not_null
        tests:
          - not_null
          - accepted_values:
              values: ['STRING', 'INTEGER', 'BIGINT', 'DOUBLE', 'BOOLEAN', 'DATE', 'TIMESTAMP', 'DATETIME']
      - name: nullable
        data_type: boolean
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: active
        data_type: boolean
        constraints:
          - type: not_null
        tests:
          - not_null
