name: "edbi"
version: "1.0.0"

profile: "databricks"

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["tests"]
# analysis-paths: ["analyses"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

seeds:
  edbi:
    config:
      +database: edbi_teamg01
      +schema: config
    reference:
      +database: edbi_teamg01
      +schema: reference

models:
  edbi:
    +persist_docs:
      relation: true
      columns: true
    bronze:
      +database: edbi_teamg01
      +schema: bronze
      +materialized: incremental
      +tags: ["bronze"]
    silver:
      +database: edbi_teamg01
      +schema: silver
      +materialized: incremental
      +tags: ["silver"]
    gold:
      +database: edbi_teamg01
      +schema: gold
      +materialized: table
      +tags: ["gold"]
