name: "edbi"
version: "1.0.0"

profile: "databricks"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
# analysis-paths: ["analyses"]
# test-paths: ["tests"]
# seed-paths: ["seeds"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

models:
  edbi:
    bronze:
      +schema: bronze
      +materialized: incremental
      +tags: ["bronze"]
    silver:
      +schema: silver
      +materialized: incremental
      +tags: ["silver"]
    gold:
      +schema: gold
      +materialized: table
      +tags: ["gold"]
