version: 2

models:
  - name: ext_criliti_sc
    description: "Deduplicated + Validated Raw Metadata for SC Court Cases"
    columns:
      - name: accused_name
        description: "Name of accused person involved in the court case"
      - name: case_no
        description: "Business key identifying the court case"
        tests:
          - not_null
      - name: case_pid
        description: "Primary key identifying the court case process instance"
        tests:
          - not_null
      - name: case_status
        description: "Status of court case"
      - name: case_title
        description: "Title of court case"
      - name: directorate
        description: "Cluster and Team in charge of the court case"
      - name: accused_dob
        description: "Date of birth of accused person involved in the court case"
      - name: accused_gender
        description: "Gender of accused person involved in the court case"
      - name: Q_IODETAILS
        description: "JSON list of Investigation Officers"
      - name: _rescued_data
        description: "JSON list of columns with data issues"
      - name: _source_file
        description: "Name of source file that data comes from"
      - name: _file_date
        description: "Date (YYYYMMDD) extracted from the source filename"
        tests:
          - not_null
      - name: _rejected_reason
        description: "Reason why row was rejected"
      - name: _ingested_at
        description: "Timestamp when the record was ingested into landing"
        tests:
          - not_null
      - name: _bronze_loaded_at
        description: "Timestamp when the record was ingested into bronze"
        tests:
          - not_null
  - name: cmplx_criliti_sc_assigned_lo
    description: "Deduplicated + Validated Raw Metadata for Officers Assigned to Court Cases"
    columns:
      - name: case_pid
        description: "Primary key identifying the court case process instance"
        tests:
          - not_null
      - name: cluster
        description: "Cluster of the assigned officer"
      - name: officer_name
        description: "Name of the assigned officer"
      - name: officer_id
        description: "Business key identifying the officer"
        tests:
          - not_null
      - name: team
        description: "Team of the assigned officer"
      - name: _rescued_data
        description: "JSON list of columns with data issues"
      - name: _source_file
        description: "Name of source file that data comes from"
      - name: _file_date
        description: "Date (YYYYMMDD) extracted from the source filename"
        tests:
          - not_null
      - name: _ingested_at
        description: "Timestamp when the record was ingested into landing"
        tests:
          - not_null
      - name: _bronze_loaded_at
        description: "Timestamp when the record was ingested into bronze"
        tests:
          - not_null
  - name: cmplx_criliti_sc_charge_dtls
    description: "Deduplicated + Validated Raw Metadata for Charges to the Court Case"
    columns:
      - name: case_pid
        description: "Primary key identifying the court case process instance"
        tests:
          - not_null
      - name: charge_no
        description: "Business key identifing the charge in the court case"
      - name: charge_type
        description: "Whether it is a District or Magistrate charge"
      - name: charge_status
        description: "Whether the charge is currently active or has been disposed"
      - name: offence_date
        description: "Date when the offence took place (YYYYMMDD)"
      - name: filing_date
        description: "Date when the charge was filed (YYYYMMDD)"
      - name: _rescued_data
        description: "JSON list of columns with data issues"
      - name: _source_file
        description: "Name of source file that data comes from"
      - name: _file_date
        description: "Date (YYYYMMDD) extracted from the source filename"
        tests:
          - not_null
      - name: _ingested_at
        description: "Timestamp when the record was ingested into landing"
        tests:
          - not_null
      - name: _bronze_loaded_at
        description: "Timestamp when the record was ingested into bronze"
        tests:
          - not_null
  - name: cmplx_criliti_sc_offence
    description: "Deduplicated + Validated Raw Metadata for Offence Information to the Charge"
    columns:
      - name: case_pid
        description: "Primary key identifying the court case process instance"
        tests:
          - not_null
      - name: charge_no
        description: "Business key identifying the charge in the court case"
      - name: act_title
        description: "Title of the act under which the accused is being charged"
      - name: reference
        description: "Section and/or sub-section of the act under which the accused is being charged"
      - name: rwpu_base
        description: "Whether it is the main offence, read-with offence, or punishable-under offence"
      - name: description
        description: "Description of the offence (act and reference) under which the accused is being charged"
      - name: _rescued_data
        description: "JSON list of columns with data issues"
      - name: _source_file
        description: "Name of source file that data comes from"
      - name: _file_date
        description: "Date (YYYYMMDD) extracted from the source filename"
        tests:
          - not_null
      - name: _ingested_at
        description: "Timestamp when the record was ingested into landing"
        tests:
          - not_null
      - name: _bronze_loaded_at
        description: "Timestamp when the record was ingested into bronze"
        tests:
          - not_null
  - name: tb_criliti_sc_court_events
    description: "Deduplicated + Validated Raw Metadata for Court Events"
    columns:
      - name: start_datetime
        description: "Start Date and Time (YYYYMMDD HH:MM) of court event"
      - name: end_datetime
        description: "End Date and Time (YYYYMMDD HH:MM) of court event"
      - name: case_pid
        description: "Primary key identifying the court case process instance"
        tests:
          - not_null
      - name: court_event_id
        description: "Primary key identifying the court event"
        tests:
          - not_null
      - name: court_number
        description: "Courtroom number where the court event took place"
      - name: court_event_type
        description: "Type of court event (e.g. First Mention, Plea, Trial, Sentencing etc)"
      - name: court_event_status
        description: "Whether the court event proceeded (new), was vacated or voided"
      - name: _rescued_data
        description: "JSON list of columns with data issues"
      - name: _source_file
        description: "Name of source file that data comes from"
      - name: _file_date
        description: "Date (YYYYMMDD) extracted from the source filename"
        tests:
          - not_null
      - name: _ingested_at
        description: "Timestamp when the record was ingested into landing"
        tests:
          - not_null
      - name: _bronze_loaded_at
        description: "Timestamp when the record was ingested into bronze"
        tests:
          - not_null
  - name: tb_criliti_sc_court_event_off
    description: "Deduplicated + Validated Raw Metadata for Officers Assigned to each Court Event"
    columns:
      - name: court_event_id
        description: "Primary key identifying the court event"
        tests:
          - not_null
      - name: officer_id
        description: "Primary key identifying the officer"
        tests:
          - not_null
      - name: officer_name
        description: "Name of the officer who attended the court event"
      - name: officer_division
        description: "Division to which the officer belongs"
      - name: _rescued_data
        description: "JSON list of columns with data issues"
      - name: _source_file
        description: "Name of source file that data comes from"
      - name: _file_date
        description: "Date (YYYYMMDD) extracted from the source filename"
        tests:
          - not_null
      - name: _ingested_at
        description: "Timestamp when the record was ingested into landing"
        tests:
          - not_null
      - name: _bronze_loaded_at
        description: "Timestamp when the record was ingested into bronze"
        tests:
          - not_null
  - name: info_extracted
    description: "Extracted information from Charge Sheets"
    columns:
      - name: case_no
        description: "Business key identifying the court case"
      - name: charge_no
        description: "Business key identifying the charge in the court case"
      - name: entity_name
        description: "Entity Name"
      - name: entity_type
        description: "Whether this is the Accused Person or Victim"
      - name: entity_age
        description: "Age of Entity at time of offence"
      - name: entity_gender
        description: "Gender of Entity"
      - name: relationship_to_victim
        description: "Relationship of the Entity to the Victim (if available)"
      - name: offence_group
        description: "Categorisation of the offence based on the extracted information"
      - name: special_type
        description: "Offence Subcategories of interest"
      - name: _rescued_data
        description: "JSON list of columns with data issues"
      - name: _source_file
        description: "Name of source file that data comes from"
      - name: _file_date
        description: "Date (YYYYMMDD) extracted from the source filename"
        tests:
          - not_null
      - name: _ingested_at
        description: "Timestamp when the record was ingested into landing"
        tests:
          - not_null
      - name: _bronze_loaded_at
        description: "Timestamp when the record was ingested into bronze"
        tests:
          - not_null
