version: 1

sources:
  - name: landing
    database: edbi_teamg01
    schema: landing
    tables:
      - name: ext_criliti_sc
        description: "Raw Metadata for SC Court Cases"
        columns:
          - name: accusedname
            description: "Name of accused person involved in the court case"
          - name: caseno
            description: "Business key identifying the court case"
            tests:
              - not_null
          - name: casepid
            description: "Primary key identifying the court case process instance"
            tests:
              - not_null
          - name: casestatus
            description: "Status of court case"
          - name: casetitle
            description: "Title of court case"
          - name: directorate
            description: "Cluster and Team in charge of the court case"
          - name: dob
            description: "Date of birth of accused person involved in the court case"
          - name: gender
            description: "Gender of accused person involved in the court case"
          - name: Q_IODETAILS
            description: "JSON list of Investigation Officers"
          - name: _source_file
            description: "Name of source file that data comes from"
          - name: _file_date
            description: "Date (YYYYMMDD) extracted from the source filename"
            tests:
              - not_null
          - name: _ingested_at
            description: "Timestamp when the record was ingested into landing"
            tests:
              - not_null
